language: c
group: travis_latest

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
  - os: osx
    install:
    - brew update > /dev/null
    - brew install gcc > /dev/null
  - os: windows
    install:
    - cinst -y ninja
    - cmake -G Ninja -B build
    - cmake --build build

install:
- cmake -B build
- cmake --build build

script:
- cd build
- ctest --output-on-failure
