language: c
fast_finish: true

os:
  - linux
#  - osx  Travis-CI segfault for all repos !?
  
env: FC=gfortran

group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages: 
      - gfortran

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true > /dev/null;
      brew link --overwrite gcc > /dev/null;
    fi

install: 
    - cd bin
    - cmake ..
    - make
    
script:
  - make test

after_failure:
  - ctest -V
