language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true
  
env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
  - os: osx
    install:
    - brew update > /dev/null
    - brew install gcc > /dev/null
  - os: windows
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .

install:
- cd build
- cmake ..
- cmake --build .

script: ctest --output-on-failure

