name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.f"
      - "**/*.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_PARALLEL_LEVEL: 4


jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake -B build

    - run: cmake --build build

    - run: ctest --test-dir build
